### ISSUE TITLE
Separate "name" and "slug" for module names

### ISSUE THREAD

**Issue by mirkoboehm** [QMSTR/qmstr-all#105] opened 2018-07-07 08:39 UTC
We should differentiate between the full name of a module, which is mainly human readable and could be more like a short sentence ("internal HTML reports with warnings and errors", "HTML reports"), and "slugs" which are short, file-system sanitized names that are unique within one master. All directories should use the slug as their name, not the instance name.

**Comment by hemarkus** [comment] 2018-08-08 11:47
is this duplicate of #57 ?

**Comment by mirkoboehm** [comment] 2018-08-08 18:15
Yes. I also think it is mostly done already. The only thing that could possibly be added is that the user can set the "slug", instead of having it automatically created by the master. This may make it easier to find output data in the results.

**Comment by hemarkus** [comment] 2019-05-09 09:44
https://github.com/QMSTR/qmstr/pull/310

**Closed by hemarkus** 2019-05-09 09:44 UTC
